server:
  port: 8080
  servlet:
    session:
      timeout: 30m

spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://mydb.c72ss0somxra.ap-northeast-2.rds.amazonaws.com:3306/cooperation?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      username: ${MYSQL_ID}
      password: ${MYSQL_PWD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false  # spring.jpa.open-in-view 설정 명시
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect  # MySQL8Dialect 대신 MySQLDialect 사용